import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import vm from 'node:vm';
const page = await readFile(new URL('../wwwroot/index.html', import.meta.url), 'utf8');
const adapter = [...page.matchAll(/<script>([\s\S]*?)<\/script>/g)].at(-1)[1];
function host(lang = 'en', caf = true) {
  const events = [], listeners = new Map(), state = { textContent: '' };
  let receive, namespace, options;
  const context = {
    addCustomMessageListener(name, callback) { namespace = name; receive = callback; },
    start(value) { options = value; },
    addEventListener() {}, isSystemReady: () => true,
  };
  const window = {dispatchEvent(event) { events.push(event); }, addEventListener(name, callback) { listeners.set(name, callback); }};
  if (caf) window.cast = {framework: {CastReceiverContext: {getInstance: () => context}, system: {EventType: {READY: 'ready', SENDER_DISCONNECTED: 'disconnected'}, MessageType: {JSON: 'JSON'}}}};
  vm.runInNewContext(adapter, {window, URL, CustomEvent: class {constructor(type, value = {}) {this.type = type; this.detail = value.detail;}}, document: {documentElement: {lang}, getElementById: () => state}});
  return {events, listeners, state, receive, namespace, options};
}
const valid = {kind: 'vibecast_handoff', version: 1, ha_url: 'https://ha.example.test', session_id: 'session-1', broadcast_token: 't'.repeat(24)};
test('generated Cast entry is stateless with direct HA transport', () => {
  assert.match(page, /https:\/\/www.gstatic.com\/cast\/sdk\/libs\/caf_receiver\/v3\/cast_receiver_framework.js/);
  assert.match(page, /Generated by scripts\/build_vibecast.py/);
  assert.match(page, /<video class="castMediaElement" hidden>/);
  assert.match(page, /\/api\/djconnect\/v1\/session\/broadcast\/ws\//);
  assert.doesNotMatch(page, /localStorage|sessionStorage|XMLHttpRequest|\/session\/history|\/ask_dj|\/handoff\/claim/);
});
test('modeled CAF adapter retains namespace, idle policy, and read-only handoff', () => {
  const h = host(); assert.equal(h.namespace, 'urn:x-cast:com.djconnect.vibecast.v1'); assert.equal(h.options.disableIdleTimeout, false);
  h.receive({data: JSON.stringify({...valid, end_grant: 'ignored', history: 'private', locale: 'nl'})});
  assert.equal(h.events[0].type, 'djconnect-handoff');
  assert.deepEqual(JSON.parse(JSON.stringify(h.events[0].detail)), {ha_url: valid.ha_url, session_id: valid.session_id, broadcast_token: valid.broadcast_token, status_generation: 1});
  h.listeners.get('beforeunload')(); assert.equal(h.events.at(-1).type, 'djconnect-host-stop');
});
test('invalid handoffs fail closed with feedback in five languages', () => {
  const wrong = [null, {...valid, version: 2}, {...valid, kind: 'other'}, {...valid, session_id: ''}, {...valid, broadcast_token: 'short'}, ...['http://ha.test', 'https://user:pass@ha.test', 'https://ha.test/path', 'https://ha.test?q=t', 'https://ha.test/#t'].map(ha_url => ({...valid, ha_url}))];
  const messages = new Set();
  for (const lang of ['en','nl','de','fr','es']) for (const data of wrong) {
    const h = host(lang); h.receive({data}); assert.deepEqual(h.events.map(e => e.type), ['djconnect-host-stop']);
    assert.ok(h.state.textContent.length > 20); assert.ok(!h.state.textContent.includes(valid.broadcast_token)); messages.add(h.state.textContent);
  }
  assert.equal(messages.size, 5); const h = host(); h.receive({data: '{'}); assert.equal(h.events[0].type, 'djconnect-host-stop');
});
test('without CAF no sender message or HA request is invented', () => {const h = host('en', false); assert.equal(h.receive, undefined); assert.equal(h.events.length, 0);});
test('Pages privacy headers cover root, index, clean URL and metadata', async () => {
  const headers = await readFile(new URL('../wwwroot/_headers', import.meta.url), 'utf8'); assert.match(headers, /^\/\*\n/);
  for (const line of ['Cache-Control: no-store','Referrer-Policy: no-referrer','X-Content-Type-Options: nosniff']) assert.ok(headers.includes(line));
  assert.doesNotMatch(headers, /Access-Control-Allow|public, max-age/);
});
